apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  APP_ENV: prod
  APP_DEBUG: "0"
  POSTGRES_DB: tsundoku
  POSTGRES_USER: postgres_user
  DATABASE_URL: postgresql://postgres_user:postgres_password@postgres:5432/tsundoku
  MONGO_URL: mongodb://mongo_root:mongo_password@mongodb:27017/tsundoku