apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
data:
  JWT_SECRET_KEY: c3VwZXJfc2VjcmV0X2tleQ==
  JWT_REFRESH_SECRET_KEY: YW5vdGhlcl9zZWNyZXRfa2V5
  POSTGRES_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmQ=
  MONGO_INITDB_ROOT_PASSWORD: bW9uZ29fcGFzc3dvcmQ=
  MONGO_INITDB_ROOT_USERNAME: bW9uZ29fcm9vdA==
  MONGO_INITDB_DATABASE: dHN1bmRva3U=