name: Build & Push Docker Images

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io
      IMAGE_PREFIX: ghcr.io/tsundoku-group

    steps:
      - name: Checkout infrastructure
        uses: actions/checkout@v3

      - name: Checkout backend
        uses: actions/checkout@v3
        with:
          repository: tsundoku-group/backend
          token: ${{ secrets.GITHUB_TOKEN }}
          path: backend

      - name: Checkout frontend
        uses: actions/checkout@v3
        with:
          repository: tsundoku-group/frontend
          token: ${{ secrets.GITHUB_TOKEN }}
          path: frontend

      - name: Set image tag date
        run: echo "DATE_TAG=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push PHP Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ../infrastructure/docker/php/prod/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX }}/php:prod
            ${{ env.IMAGE_PREFIX }}/php:${{ github.sha }}
            ${{ env.IMAGE_PREFIX }}/php:${{ env.DATE_TAG }}

      - name: Build & Push Next.js Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ../infrastructure/docker/nextjs/prod/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX }}/nextjs:prod
            ${{ env.IMAGE_PREFIX }}/nextjs:${{ github.sha }}
            ${{ env.IMAGE_PREFIX }}/nextjs:${{ env.DATE_TAG }}

      - name: Build & Push Nginx Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./infrastructure/docker/nginx/prod/conf.d/default.conf
          push: true
          tags: |
            ${{ env.IMAGE_PREFIX }}/nginx:prod
            ${{ env.IMAGE_PREFIX }}/nginx:${{ github.sha }}
            ${{ env.IMAGE_PREFIX }}/nginx:${{ env.DATE_TAG }}